### ISSUE TITLE
意思是“要好好的”？

### ISSUE THREAD

**Issue by Yinke7** [yaogoodgoodde/SimpleNfc#1]
这个项目可以直接安装到手机上使用吗？

**Comment by yaogoodgoodde** [comment]
> 这个项目可以直接安装到手机上使用吗？

可以直接运行，代码我都跑通了。

**Comment by yaogoodgoodde** [comment]
哈哈 是的 要好好的

**Comment by Yinke7** [comment]
兄弟，怎么跑哟，我是做硬件的，没接触过安卓。
是需要编译你的源码，刷进手机，还是安装apk？（我在项目中没找到apk。。。）

**Comment by yaogoodgoodde** [comment]
> 兄弟，怎么跑哟，我是做硬件的，没接触过安卓。
> 是需要编译你的源码，刷进手机，还是安装apk？（我在项目中没找到apk。。。）

我打包上传了一下apk，你试试能不能用

**Comment by Yinke7** [comment]
> > 兄弟，怎么跑哟，我是做硬件的，没接触过安卓。
> > 是需要编译你的源码，刷进手机，还是安装apk？（我在项目中没找到apk。。。）
> 
> 我打包上传了一下apk，你试试能不能用

好的，谢谢，apk我安装好了；但是我忘了我手机没集成nfc，有点小尴尬，我找个NFC手机再试试
